language: r
# dist: bionic # Uncomment until fix of https://travis-ci.community/t/r-install-broken-travis-ci-rstudio-org-returns-403/9640
cache: packages

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - richelbilderbeek/mhcnuggetsr

before_script:
  - Rscript -e 'mhcnuggetsr::install_mhcnuggets()'

script:
  - travis_wait 60 R CMD build .
  - travis_wait 60 R CMD check *tar.gz
  - Rscript -e 'remotes::install_github("richelbilderbeek/mhcnpreds", ref = "develop")'
  - sudo apt install r-cran-lubridate
  - Rscript scripts/measure_speed/measure_speed.R

after_success:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'goodpractice::gp()'
  - Rscript -e 'mhcnuggetsr::mhcnuggetsr_report()'

after_failure:
  - Rscript -e 'mhcnuggetsr::mhcnuggetsr_report()'
  - pwd
  - find . | egrep "fasta"



