language: R
dist: bionic
cache: packages

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - richelbilderbeek/mhcnuggetsr


before_script:
  - Rscript -e 'mhcnuggetsr::install_mhcnuggets()'

after_success:
  - Rscript scripts/measure_speed/measure_speed.R
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'goodpractice::gp()'
  - Rscript -e 'mhcnuggetsr::mhcnuggetsr_report()'

after_failure:
  - Rscript -e 'mhcnuggetsr::mhcnuggetsr_report()'
  - pwd
  - find . | egrep "fasta"



